name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  Tests:
    name: ${{ matrix.os }} / ${{ matrix.python-version }}
    runs-on: ${{ matrix.image }}
    strategy:
      matrix:
        os: [Ubuntu, macOS, Windows]
        python-version: ["3.11", "3.12"]
        include:
          - os: Ubuntu
            image: ubuntu-22.04
          - os: Windows
            image: windows-2022
          - os: macOS
            image: macos-13
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry

      - name: Set environment variable
        run: echo "PYTHONUTF8=1" >> $GITHUB_ENV

      - name: Install dependencies
        run: poetry install

      - name: Check code format and typechecking
        run: poetry run pre-commit run --all-files -vvv

      - name: Run tests
        run: poetry run pytest tests -s
