name: Bump version

on:
  push:
    branches:
      - dev

jobs:
  bump-version:
    if: "!startsWith(github.event.head_commit.message, '🔖 release:')"
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          token: "${{ github.token }}"
          fetch-depth: 0

      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ github.token }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: "CHANGELOG.md"
          tag_name: ${{ env.REVISION }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
