name: Pyproject Creator CI

on:
  push:
    branches: ["master"]
  pull_request:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Lint with pre-commit
        uses: pre-commit/action@v3.0.1
      - name: Install poetry via pipx
        run: |
          python -m pip install --upgrade pip
          pip install --user pipx
          pipx ensurepath
          pip install poetry
      - name: Install dependencies via poetry
        run: |
          poetry install
      - name: Test with pytest
        run: |
          poetry run pytest tests -s
